currentFoodBanks = [
    "The Salvation Army of Birmingham",
    "Project Hopewell",
    "Urban Ministry",
    "United Community Center",
    "Community Kitchens at St. Andrews Episcopal Church",
    "Woodlawn United Methodist Church",
    "Feeding Alabama",
    "Athens-Limestone Food and Shelter",
    "Food Bank of North Alabama",
    "West Alabama Food Bank",
    "Food Bank of East Alabama",
    "Selma Area Food Bank",
    "Feeding the Gulf Coast",
    "Wiregrass Area Food Bank",
    "Food Bank of Alaska",
    "Fairbanks Community Food Bank",
    "Blood n Fire Food and Clothing Pantry",
    "Bristol Bay Native Association Food Bank",
    "Community Covenant Church of Fairbanks Food Bank",
    "Douglas United Methodist Church Food Pantry",
    "F.I.S.H.",
    "Azcend",
    "The Comfort Food Pantry",
    "United Food Bank",
    "Matthew's Crossing Food Bank",
    "Interfaith Cooperative Ministries",
    "Association of Arizona Food Banks",
    "The Cultural Cup Food Bank",
    "Agua Fria Food and Clothing Bank - Avondale",
    "Community Food Pantry of Benzon AZ",
    "First Harvest Food Pantry",
    "Abiding Ministries",
    "Arizona Food Bank Network",
    "Havasu Community Health Foundation",
    "Food Bank of the Rockies",
    "Care and Share Food Bank for Southern Colorado",
    "North Denver Cares Food Bank",
    "Food Bank for Larimer County",
    "Weld Food Bank",
    "Hope Starts Here Food Bank",
    "Community Food Bank",
    "Food Bank for Larimer County",
    "Feeding Colorado",
    "Milton Community Food Pantry",
    "Food Bank of Delaware",
    "Lutheran Community Services",
    "Second Harvest Food Bank",
    "Second Harvest Food Bank Marion Branch",
    "Second Harvest Food Bank Volusia Branch",
    "Second Harvest Food Bank Brevard Branch",
    "Feeding South Florida",
    "Bread of The Mighty Food Bank",
    "Palm Beach Harvest",
    "All Faiths Food Bank",
    "America's Second Harvest of the Big Bend",
    "Feeding Northeast Florida",
    "Feeding The Gulf Coast",
    "Treasure Coast Food Bank",
    "Feeding Tampa Bay",
    "Food Bank of Northeast Georgia",
    "Atlanta Community Food Bank",
    "Feeding The Valley",
    "America’s Second Harvest of Coastal Georgia",
    "Middle Georgia Community Food Bank",
    "Hawai'i Foodbank",
    "The Food Basket",
    "Maui Food Bank",
    "The Pantry by Feeding Hawaii Together",
    "Susannah Wesley Community Center",
    "A Just Harvest",
    "Common Pantry",
    "Irving Park Community Food Pantry",
    "Lakeview Pantry",
    "Greater Chicago Food Depository",
    "Cornerstone Community Outreach",
    "St. Margaret of Scotland Parish",
    "Chicago Food Pantry",
    "Central Illinois Foodbank",
    "Eastern Illinois Foodbank",
    "Peoria Area Food Bank",
    "Feeding Louisiana",
    "Food Bank of Northwest Louisiana",
    "Food Bank of Central Louisiana",
    "Greater Baton Rouge Food Bank",
    "Second Harvest Food Bank",
    "Food Bank of Northeast Louisiana",
    "St. Martin's Pantry",
    "Zion Pentecostal Food Pantry",
    "Burlington Food Pantry",
    "UVEC Food Pantry",
    "Agape Food Pantry",
    "Patten Community Food Cupboard",
    "I Care Ministries",
    "Chester Baptist Food Pantry",
    "Lincoln Regional Food Cupboard",
    "The Greater Boston Food Bank",
    "The Food Bank of Western Massachusetts",
    "Merrimack Valley Food Bank",
    "ABCD Allston-Brighton",
    "ABCD Jamaica Plain",
    "ABCD North End/West End",
    "ABCD Parker Hill/Fenway",
    "ABCD Roxbury/North Dorchester",
    "Allston Brighton Food Pantry",
    "Barre Food Pantry",
    "Bread of Life - Malden",
    "Caregiving Network",
    "Gleaners Community Food Bank of Southeastern Michigan",
    "Greater Lansing Food Bank",
    "Community Food Bank of Macomb County",
    "Catholic Charities of Southeast Michigan",
    "Macomb Community Action Center",
    "Veteran’s Food Bank",
    "Hope Center",
    "Mid City Nutrition",
    "Agape Center",
    "Open Hands Food Pantry",
    "North Country Food Bank",
    "Northern Lakes Food Bank",
    "Second Harvest",
    "The Food Group",
    "Hunger Solutions",
    "North Central Food Bank",
    "Neighborhood House",
    "Minnehaha Food Shelf",
    "SACA Food Shelf",
    "The Camden Promise Food Shelf",
    "Mississippi Food Network",
    "Heartland Hands",
    "Extra Table",
    "Hunger Coalition of Northeast Mississippi",
    "Mission Okolona Food Pantry",
    "Ole Miss Food Bank",
    "HeartLand Hands",
    "Hearty Helpings Food Pantry",
    "F.A.I.T.H Food Pantry",
    "Grenada Food Pantry",
    "The Caring Center",
    "Crosslines",
    "Ozarks Food Harvest",
    "Salvation Army Springfield",
    "Victory Mission Food Pantry",
    "Well Of Life Food Pantry",
    "Bishop Sullivan Center Food Pantry",
    "Della Lamb Food Pantry",
    "Harvesters",
    "Neighbors Helping Neighbors Mobile Food Panty",
    "Headwaters Area Food Bank",
    "Granite County Food Pantry",
    "Custer County Food Bank",
    "The Food Pantry",
    "West Yellowstone Food Bank",
    "Community Food Bank of Mineral County",
    "Troy Food Pantry",
    "Twin Bridges Food Pantry",
    "Plains Community Food Bank",
    "Tobacco Valley Food Pantry",
    "Wibaux Food Bank",
    "BVCA Food Pantry",
    "BVCA Food Pantry",
    "FaithWorks Pantry",
    "Food Bank for the Heartland",
    "Heart Ministry Center Food Pantry",
    "Loaves and Fishes Food Pantry",
    "Project Hope",
    "Kearney Jubilee Center Food Pantry",
    "Community Action Partnership of Mid-Nebraska",
    "Food Bank of Lincoln",
    "Matt Talbot Kitchen & Outreach",
    "Northeast Area Pantry",
    "Community Action Partnership of Strafford County",
    "Gerry's Food Pantry",
    "New Hampshire Food Bank",
    "Salvation Army Nashua",
    "Sacred Heart Church Food Pantry",
    "Hands Across the Table",
    "Laconia Salvation Army",
    "St. Vincent de Paul Food Pantry",
    "The Friendly Kitchen",
    "Seacoast Family Food Pantry",
    "Great Plains Food Bank",
    "Jamestown Region Community Action Partnership",
    "Bismarck Region Community Action Partnership",
    "Corpus Christi Food Pantry",
    "Heavens Helpers Soup Cafe",
    "Luther's Kitchen",
    "Sargent County Food Pantry",
    "Richland Wilkin Food Pantry",
    "May-Port Food Pantry",
    "Akron-Canton Regional Foodbank",
    "Akron-Canton Regional Foodbank",
    "Greater Cleveland Food Bank",
    "Freestore Foodbank",
    "Mid-Ohio Food Bank",
    "Second Harvest Food Bank of North Central Ohio",
    "Second Harvest Food Bank of the Mahoning Valley",
    "Second Harvest Foodbank of Clark, Champaign, & Logan",
    "Shared Harvest Foodbank",
    "HAPCAP",
    "Dayton Foodbank",
    "Toledo Northwestern Ohio Food Bank",
    "West Ohio Food Bank",
    "County East FRC Food Pantry",
    "County West FRC Food Pantry",
    "Eastside FRC Food Pantry",
    "Southside FRC Food Pantry",
    "Baldwinsville Community Food Pantry",
    "Blessed Sacrament Food Pantry",
    "Calvary Food Pantry",
    "Buffalo Urban League Food Pantry",
    "FeedMore Western NY",
    "New Beginnings Food Pantry",
    "Polonia Hall Food Pantry",
    "St. Vincent DePaul Food Recovery Network",
    "Neighbor Impact Food Bank",
    "ACCESS",
    "Neighborhood Center of South Morrow County",
    "Outreach Food Pantry",
    "FOOD for Lane County",
    "Food Share of Lincoln County",
    "Klamath/Lake Counties Food Bank",
    "Marion Polk Food Share",
    "Oregon Food Bank",
    "UCAN Food Shares",
    "YCAP Food Bank",
    "Food Bank of Eastern Oklahoma",
    "Regional Food Bank of Oklahoma",
    "Lawton Food Bank",
    "BritVil Community Food Pantry",
    "Reaching Our City Food Pantry",
    "Cornerstone Food Pantry",
    "Feeding South Dakota",
    "Blue Ridge Area Food Bank",
    "Feeding America Southwest Virginia",
    "Feed More",
    "Foodbank of Southeastern Virginia",
    "FoodBank of the Virginia Peninsula",
    "Fredericksburg Area Food Bank",
    "Food Lifeline",
    "Second Harvest"
]
